apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  myapp
spec:
  selector:
    matchLabels:
      app: ahmed 
  replicas: 3
  template:
    metadata:
      name: ahmed 
      labels:
        app: ahmed      
    spec:
      containers:
        - image: asd200/ahmed200
          name:  my-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "1"
            requests:
              memory: "100Mi"    
     
              